# Generated by Django 3.2.6 on 2021-08-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='publicspeaking',
            name='website',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='sports',
            name='website',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='stem',
            name='website',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='summercamps',
            name='website',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='tutoring',
            name='website',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='youthemployment',
            name='website',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publicspeaking',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publicspeaking',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='publicspeaking',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sports',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sports',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sports',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stem',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stem',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='summercamps',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='summercamps',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='summercamps',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tutoring',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tutoring',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tutoring',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='youthemployment',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='youthemployment',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='youthemployment',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
